version: '3.7'
name: wks-platform
services:

    camunda:
        image: ${CAMUNDA_DOCKER_IMAGE}:${CAMUNDA7_VERSION}
        command: ./camunda.sh --rest --webapps
        ports:
            - 8080:8080
        healthcheck:
            test: curl --fail http://localhost:8080/engine-rest/version || exit 1
            interval: 10s
            retries: 3
            start_period: 5s
            timeout: 10s
        depends_on:
            mongodb:
                condition: service_healthy
                
    case-engine-rest-api:
        image: ghcr.io/wkspower/case-engine-rest-api:${TAG}
        ports:
            - 8081:8081
        links:
            - mongodb
            - camunda
        environment:
            - CAMUNDA_VERSION=camunda7
            - CAMUNDA_BASE_URL=${CAMUNDA_BASE_URL}
            - MONGO_DATABASE=${MONGO_WKS_DATABASE}
            - MONGO_CONN=${MONGO_CONNECTION_URL}
            - KEYCLOAK_URL=${KEYCLOAK_URL}
            - OPA_URL=${OPA_URL}
        depends_on:
            mongodb:
                condition: service_healthy
            camunda:
                condition: service_healthy

    c7-external-tasks:
        image: ghcr.io/wkspower/c7-external-tasks:${TAG}
        links:
            - camunda
            - case-engine-rest-api
        environment:
            - CAMUNDA_BASE_URL=${CAMUNDA_BASE_URL}
            - CAMUNDA_USERNAME=${CAMUNDA_USERNAME}
            - CAMUNDA_PASSWORD=${CAMUNDA_PASSWORD}
            - KEYCLOAK_URL=${KEYCLOAK_TOKEN_URL}
            - WKS_CASE_API_URL=${WKS_CASE_API_URL}
            - WEBSOCKET_ENABLED=${WEBSOCKET_ENABLED}
            - DISABLE_BACKOFF_STRATEGY=${DISABLE_BACKOFF_STRATEGY}
        depends_on:
            camunda:
                condition: service_healthy